name : Foundation5/github pages/Jykill starter
brand : MagnetsAreRad
description : Home of the DotMatrix™ Photo Gallery Wall Kit
keyword : 
url : https://magnetsarerad.com
email : support@magnetsarerad.com
twitter : MagnetsAreRad
github : empirenine
author : Mike MacDonald
analytics : UA-68276202-1
year : 2015
markdown : kramdown
exclude :
  - node_modules
